// Offline Keyword to Emoji Mapping Dictionary
export const EMOJI_KEYWORD_MAP: Record<string, string> = {
  money: '💰',
  cash: '💵',
  dollar: '💲',
  rich: '🤑',
  profit: '📈',
  fire: '🔥',
  lit: '🔥',
  rocket: '🚀',
  boom: '💥',
  growth: '📈',
  idea: '💡',
  think: '🧠',
  mind: '🧠',
  brain: '🧠',
  shock: '😱',
  wow: '😲',
  crazy: '🤪',
  stop: '🛑',
  warning: '⚠️',
  alert: '🚨',
  time: '⏱️',
  clock: '⏰',
  watch: '⌚',
  fast: '⚡',
  lightning: '⚡',
  energy: '⚡',
  power: '💪',
  strong: '💪',
  win: '🏆',
  winner: '🥇',
  target: '🎯',
  goal: '🎯',
  secret: '🤫',
  shh: '🤫',
  key: '🔑',
  lock: '🔒',
  unlock: '🔓',
  love: '❤️',
  heart: '❤️',
  star: '⭐',
  magic: '✨',
  sparkle: '✨',
  question: '❓',
  why: '🤔',
  how: '⚙️',
  look: '👀',
  watchout: '👁️',
  search: '🔍',
  top: '🔝',
  best: '👑',
  king: '👑',
  queen: '👑',
  game: '🎮',
  play: '▶️',
  music: '🎵',
  sound: '🔊',
  voice: '🎙️',
  phone: '📱',
  call: '📞',
  computer: '💻',
  tech: '🤖',
  ai: '🤖',
  robot: '🤖',
  world: '🌍',
  global: '🌐',
  food: '🍕',
  drink: '☕',
  sleep: '😴',
  run: '🏃',
  fitness: '🏋️',
  car: '🚗',
  speed: '🏎️',
  airplane: '✈️',
  house: '🏠',
  home: '🏡',
  death: '💀',
  skull: '💀',
  danger: '☠️',
  ghost: '👻',
  check: '✅',
  cross: '❌',
  no: '🚫',
  yes: '👍',
  bad: '👎',
  party: '🎉',
  gift: '🎁',
  hundred: '💯',
  clutch: '👑',
  ace: '🎯',
  headshot: '🎯',
  kill: '💀',
  dead: '💀',
  died: '💀',
  pog: '😲',
  gg: '🎮',
  gamer: '🎮',
  lmao: '🤣',
  omg: '😱',
  rage: '🤬',
  noob: '🤡',
  pro: '🏆',
  streamer: '🎙️',
  clip: '🎬',
  epic: '⚡',
  fail: '💥',
  insane: '🤯',
  bro: '🗣️',
  hype: '🔥',
  shot: '💥',
  victory: '🏆',
};

export function getEmojiForWord(wordText: string): string | undefined {
  const clean = wordText.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (EMOJI_KEYWORD_MAP[clean]) {
    return EMOJI_KEYWORD_MAP[clean];
  }
  // Try partial match
  for (const [key, emoji] of Object.entries(EMOJI_KEYWORD_MAP)) {
    if (clean.length > 3 && (clean.includes(key) || key.includes(clean))) {
      return emoji;
    }
  }
  return undefined;
}
