import { PresetTheme } from '../types';

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: 'hormozi_viral',
    name: '🔥 Hormozi Pop',
    platform: 'tiktok',
    description: 'Ultra high-converting bold yellow active text with heavy black outline.',
    style: {
      fontFamily: '"Bebas Neue", Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#FFE600', // Bright Yellow
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowBlur: 10,
      shadowOffsetY: 4,
      animationType: 'pop',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'beast_red_punch',
    name: '🥊 Beast Red Punch',
    platform: 'youtube_shorts',
    description: 'High-impact MrBeast style bold text with vibrant crimson red active words.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#FF2E4D', // Crimson Red
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: '#000000',
      backgroundOpacity: 0.9,
      activeWordBgColor: '#FF2E4D',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 46, 77, 0.5)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'pop',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
    },
  },
  {
    id: 'gamer_hype_neon',
    name: '🎮 Streamer Neon',
    platform: 'tiktok',
    description: 'Electric cyan & magenta glowing caption style for viral streaming clips.',
    style: {
      fontFamily: '"Chakra Petch", sans-serif',
      fontSize: 52,
      activeWordColor: '#00F0FF', // Neon Cyan
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 5, 12, 0.9)',
      backgroundOpacity: 0.9,
      activeWordBgColor: 'rgba(0, 240, 255, 0.25)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 240, 255, 0.7)',
      shadowBlur: 20,
      shadowOffsetY: 0,
      animationType: 'neon_glow',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'gamer_clutch_gold',
    name: '👑 Gaming Clutch & Ace',
    platform: 'youtube_shorts',
    description: 'Gold & crimson Bento box style for epic wins and tournament plays.',
    style: {
      fontFamily: '"Russo One", sans-serif',
      fontSize: 50,
      activeWordColor: '#FFD700', // Gold
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: '#090D16',
      backgroundOpacity: 0.95,
      activeWordBgColor: '#FFD700',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(255, 215, 0, 0.4)',
      shadowBlur: 14,
      shadowOffsetY: 3,
      animationType: 'bento_box',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.18,
    },
  },
  {
    id: 'shorts_electric_green',
    name: '⚡ Shorts Electric',
    platform: 'youtube_shorts',
    description: 'Neon green active word with dark background pill and bounce.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 48,
      activeWordColor: '#00FF66', // Electric Green
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 10, 15, 0.85)',
      backgroundOpacity: 0.85,
      activeWordBgColor: 'rgba(0, 255, 102, 0.25)',
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(0,0,0,0.6)',
      shadowBlur: 8,
      shadowOffsetY: 2,
      animationType: 'bounce',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 65,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'reels_cyan_gradient',
    name: '✨ Reels Cyan Pulse',
    platform: 'instagram_reels',
    description: 'Vibrant cyan text with glowing backdrop, sleek modern Instagram look.',
    style: {
      fontFamily: '"Plus Jakarta Sans", Outfit, sans-serif',
      fontSize: 46,
      activeWordColor: '#00F0FF', // Cyan
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      backgroundOpacity: 0.75,
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0, 240, 255, 0.5)',
      shadowBlur: 16,
      shadowOffsetY: 0,
      animationType: 'neon_glow',
      maxWordsPerLine: 3,
      textTransform: 'none',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.1,
    },
  },
  {
    id: 'bento_box_gold',
    name: '🏆 Bento High Contrast',
    platform: 'tiktok',
    description: 'Solid black box around words with bright gold active word highlight.',
    style: {
      fontFamily: 'Rowdies, "Archivo Black", sans-serif',
      fontSize: 50,
      activeWordColor: '#FFD700', // Gold
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: '#000000',
      backgroundOpacity: 0.95,
      activeWordBgColor: '#FFD700',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 6,
      shadowOffsetY: 4,
      animationType: 'bento_box',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 72,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.12,
    },
  },
  {
    id: 'karaoke_pink_fire',
    name: '💖 Karaoke Pink Swipe',
    platform: 'facebook_reels',
    description: 'Hot pink karaoke highlight with smooth text swipe transition.',
    style: {
      fontFamily: 'Poppins, sans-serif',
      fontSize: 46,
      activeWordColor: '#FF007F', // Hot Pink
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.7)',
      strokeColor: '#101010',
      strokeWidth: 4,
      shadowColor: 'rgba(255,0,127,0.4)',
      shadowBlur: 12,
      shadowOffsetY: 2,
      animationType: 'karaoke',
      maxWordsPerLine: 4,
      textTransform: 'capitalize',
      positionYPercent: 75,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.1,
    },
  },
  {
    id: 'toktik_viral_red',
    name: '📱 TokTik Hook Red',
    platform: 'tiktok',
    description: 'Intense crimson red pop font engineered for 3-second hook retention rates.',
    style: {
      fontFamily: '"Black Han Sans", Impact, sans-serif',
      fontSize: 52,
      activeWordColor: '#FF003C', // TikTok Red
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 10, 15, 0.9)',
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 0, 60, 0.6)',
      shadowBlur: 14,
      shadowOffsetY: 2,
      animationType: 'pop',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'synthwave_cyber_purple',
    name: '💜 Synthwave Cyber',
    platform: 'custom',
    description: 'Futuristic purple & pink neon glow with condensed bold lettering.',
    style: {
      fontFamily: 'Orbitron, sans-serif',
      fontSize: 50,
      activeWordColor: '#E024FF', // Neon Violet
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 5, 29, 0.9)',
      backgroundOpacity: 0.9,
      activeWordBgColor: 'rgba(224, 36, 255, 0.25)',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(224, 36, 255, 0.7)',
      shadowBlur: 18,
      shadowOffsetY: 0,
      animationType: 'neon_glow',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
    },
  },
  {
    id: 'golden_luxe_aura',
    name: '🌟 Golden Luxe',
    platform: 'instagram_reels',
    description: 'Premium gold metallic text with rich subtle shadow for luxury content.',
    style: {
      fontFamily: 'Cinzel, serif',
      fontSize: 46,
      activeWordColor: '#FFD700', // Gold
      inactiveWordColor: '#F1F5F9',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 12, 5, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(255, 215, 0, 0.4)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'bounce',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 72,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'volcano_orange_pop',
    name: '🌋 Volcano Orange',
    platform: 'tiktok',
    description: 'Fiery orange and bright yellow pop scale for high energy storytelling.',
    style: {
      fontFamily: 'Bungee, Impact, sans-serif',
      fontSize: 48,
      activeWordColor: '#FF6B00', // Flame Orange
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.8)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 107, 0, 0.5)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'pop',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
    },
  },
  {
    id: 'minimal_clean_white',
    name: '⚪ Clean Minimalist',
    platform: 'custom',
    description: 'Sleek white text with subtle underline and active word pulse.',
    style: {
      fontFamily: 'Urbanist, "Space Grotesk", sans-serif',
      fontSize: 44,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#94A3B8',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 6,
      shadowOffsetY: 2,
      animationType: 'minimal',
      maxWordsPerLine: 4,
      textTransform: 'none',
      positionYPercent: 80,
      positionXPercent: 50,
      emojiEnabled: false,
      autoEmojiKeywords: false,
      activeScaleFactor: 1.08,
    },
  },
  {
    id: 'dark_stealth_amber',
    name: '🖤 Dark Stealth Amber',
    platform: 'custom',
    description: 'Matte dark pill container with warm amber highlight.',
    style: {
      fontFamily: 'Syne, Montserrat, sans-serif',
      fontSize: 46,
      activeWordColor: '#F59E0B', // Amber
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: '#0F172A',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 8,
      shadowOffsetY: 2,
      animationType: 'bento_box',
      maxWordsPerLine: 3,
      textTransform: 'none',
      positionYPercent: 75,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.1,
    },
  },
  {
    id: 'cyber_glitch_chroma',
    name: '👾 Cyber Glitch',
    platform: 'tiktok',
    description: 'RGB chromatic aberration with high-tech jitter for futuristic edits.',
    style: {
      fontFamily: 'Audiowide, "Chakra Petch", sans-serif',
      fontSize: 50,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#F1F5F9',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 15, 26, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 240, 255, 0.8)',
      shadowBlur: 14,
      shadowOffsetY: 0,
      animationType: 'glitch',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'kinetic_slide_ascent',
    name: '🚀 Kinetic Slide Up',
    platform: 'youtube_shorts',
    description: 'Smooth spring float and upward slide as each spoken word drops in.',
    style: {
      fontFamily: '"Paytone One", sans-serif',
      fontSize: 48,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 10,
      shadowOffsetY: 3,
      animationType: 'slide_up',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'hype_impact_shake',
    name: '📳 Hype Tremor Punch',
    platform: 'tiktok',
    description: 'High-energy tremor vibration for punchlines, gaming kills, and shock hooks.',
    style: {
      fontFamily: '"Archivo Black", Anton, sans-serif',
      fontSize: 54,
      activeWordColor: '#FF2E4D',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 46, 77, 0.6)',
      shadowBlur: 16,
      shadowOffsetY: 4,
      animationType: 'shake',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 65,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
    },
  },
  {
    id: 'typewriter_noir_doc',
    name: '⌨️ Typewriter Noir',
    platform: 'custom',
    description: 'Live character-by-character speech reveal for storytelling and documentaries.',
    style: {
      fontFamily: '"Space Grotesk", monospace',
      fontSize: 44,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#94A3B8',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 23, 42, 0.95)',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0,0,0,0.7)',
      shadowBlur: 8,
      shadowOffsetY: 2,
      animationType: 'typewriter',
      maxWordsPerLine: 4,
      textTransform: 'none',
      positionYPercent: 75,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.08,
    },
  },
  {
    id: 'ocean_harmonic_wave',
    name: '🌊 Harmonic Wave Float',
    platform: 'instagram_reels',
    description: 'Continuous sinusoidal wave floating motion across rhythmic captions.',
    style: {
      fontFamily: 'Fredoka, sans-serif',
      fontSize: 48,
      activeWordColor: '#38BDF8',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: 'rgba(3, 7, 18, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(56, 189, 248, 0.4)',
      shadowBlur: 12,
      shadowOffsetY: 2,
      animationType: 'wave',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'classic_pulse_bounce',
    name: '💓 Pulse Bounce Classic',
    platform: 'tiktok',
    description: 'The beloved classic scale-based sine pulse bounce on active words.',
    style: {
      fontFamily: '"League Spartan", Montserrat, sans-serif',
      fontSize: 52,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 10,
      shadowOffsetY: 3,
      animationType: 'bounce_pulse',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'jelly_rubber_band',
    name: '🪀 Jelly Rubber Band',
    platform: 'youtube_shorts',
    description: 'Elastic jelly stretch and rebound on speech impact.',
    style: {
      fontFamily: 'Kanit, sans-serif',
      fontSize: 52,
      activeWordColor: '#22C55E',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 46, 22, 0.9)',
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(34, 197, 94, 0.5)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'rubber_band',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'rainbow_spectrum_wave',
    name: '🌈 Spectrum Rainbow Wave',
    platform: 'tiktok',
    description: 'Hyper-vibrant rotating chromatic hue cycling across active words.',
    style: {
      fontFamily: '"Permanent Marker", cursive',
      fontSize: 48,
      activeWordColor: '#FF007F',
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 23, 42, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(255, 0, 127, 0.6)',
      shadowBlur: 16,
      shadowOffsetY: 3,
      animationType: 'color_cycle',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'spin_drop_kinetic',
    name: '💫 360 Spin Drop Snap',
    platform: 'instagram_reels',
    description: 'High-octane 360 spin drop with instant snap lock.',
    style: {
      fontFamily: 'Staatliches, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#F59E0B',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(245, 158, 11, 0.6)',
      shadowBlur: 14,
      shadowOffsetY: 3,
      animationType: 'spin_in',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 65,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
];
