import { PresetTheme } from '../types';

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: 'hormozi_viral',
    name: '🔥 Hormozi Pop',
    platform: 'tiktok',
    description: 'Ultra high-converting bold yellow active text with heavy black outline.',
    style: {
      fontFamily: '"Bebas Neue", Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#FFE600', // Bright Yellow
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowBlur: 10,
      shadowOffsetY: 4,
      animationType: 'pop',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'beast_red_punch',
    name: '🥊 Beast Red Punch',
    platform: 'youtube_shorts',
    description: 'High-impact MrBeast style bold text with vibrant crimson red active words.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#FF2E4D', // Crimson Red
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: '#000000',
      backgroundOpacity: 0.9,
      activeWordBgColor: '#FF2E4D',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 46, 77, 0.5)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'pop',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
    },
  },
  {
    id: 'gamer_hype_neon',
    name: '🎮 Streamer Neon',
    platform: 'tiktok',
    description: 'Electric cyan & magenta glowing caption style for viral streaming clips.',
    style: {
      fontFamily: '"Chakra Petch", sans-serif',
      fontSize: 52,
      activeWordColor: '#00F0FF', // Neon Cyan
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 5, 12, 0.9)',
      backgroundOpacity: 0.9,
      activeWordBgColor: 'rgba(0, 240, 255, 0.25)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 240, 255, 0.7)',
      shadowBlur: 20,
      shadowOffsetY: 0,
      animationType: 'neon_glow',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'gamer_clutch_gold',
    name: '👑 Gaming Clutch & Ace',
    platform: 'youtube_shorts',
    description: 'Gold & crimson Bento box style for epic wins and tournament plays.',
    style: {
      fontFamily: '"Russo One", sans-serif',
      fontSize: 50,
      activeWordColor: '#FFD700', // Gold
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: '#090D16',
      backgroundOpacity: 0.95,
      activeWordBgColor: '#FFD700',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(255, 215, 0, 0.4)',
      shadowBlur: 14,
      shadowOffsetY: 3,
      animationType: 'bento_box',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.18,
    },
  },
  {
    id: 'shorts_electric_green',
    name: '⚡ Shorts Electric',
    platform: 'youtube_shorts',
    description: 'Neon green active word with dark background pill and bounce.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 48,
      activeWordColor: '#00FF66', // Electric Green
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 10, 15, 0.85)',
      backgroundOpacity: 0.85,
      activeWordBgColor: 'rgba(0, 255, 102, 0.25)',
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(0,0,0,0.6)',
      shadowBlur: 8,
      shadowOffsetY: 2,
      animationType: 'bounce',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 65,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'reels_cyan_gradient',
    name: '✨ Reels Cyan Pulse',
    platform: 'instagram_reels',
    description: 'Vibrant cyan text with glowing backdrop, sleek modern Instagram look.',
    style: {
      fontFamily: '"Plus Jakarta Sans", Outfit, sans-serif',
      fontSize: 46,
      activeWordColor: '#00F0FF', // Cyan
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      backgroundOpacity: 0.75,
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0, 240, 255, 0.5)',
      shadowBlur: 16,
      shadowOffsetY: 0,
      animationType: 'neon_glow',
      maxWordsPerLine: 3,
      textTransform: 'none',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.1,
    },
  },
  {
    id: 'bento_box_gold',
    name: '🏆 Bento High Contrast',
    platform: 'tiktok',
    description: 'Solid black box around words with bright gold active word highlight.',
    style: {
      fontFamily: 'Rowdies, "Archivo Black", sans-serif',
      fontSize: 50,
      activeWordColor: '#FFD700', // Gold
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: '#000000',
      backgroundOpacity: 0.95,
      activeWordBgColor: '#FFD700',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 6,
      shadowOffsetY: 4,
      animationType: 'bento_box',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 72,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.12,
    },
  },
  {
    id: 'karaoke_pink_fire',
    name: '💖 Karaoke Pink Swipe',
    platform: 'facebook_reels',
    description: 'Hot pink karaoke highlight with smooth text swipe transition.',
    style: {
      fontFamily: 'Poppins, sans-serif',
      fontSize: 46,
      activeWordColor: '#FF007F', // Hot Pink
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.7)',
      strokeColor: '#101010',
      strokeWidth: 4,
      shadowColor: 'rgba(255,0,127,0.4)',
      shadowBlur: 12,
      shadowOffsetY: 2,
      animationType: 'karaoke',
      maxWordsPerLine: 4,
      textTransform: 'capitalize',
      positionYPercent: 75,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.1,
    },
  },
  {
    id: 'toktik_viral_red',
    name: '📱 TokTik Hook Red',
    platform: 'tiktok',
    description: 'Intense crimson red pop font engineered for 3-second hook retention rates.',
    style: {
      fontFamily: '"Black Han Sans", Impact, sans-serif',
      fontSize: 52,
      activeWordColor: '#FF003C', // TikTok Red
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 10, 15, 0.9)',
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 0, 60, 0.6)',
      shadowBlur: 14,
      shadowOffsetY: 2,
      animationType: 'pop',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'synthwave_cyber_purple',
    name: '💜 Synthwave Cyber',
    platform: 'custom',
    description: 'Futuristic purple & pink neon glow with condensed bold lettering.',
    style: {
      fontFamily: 'Orbitron, sans-serif',
      fontSize: 50,
      activeWordColor: '#E024FF', // Neon Violet
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 5, 29, 0.9)',
      backgroundOpacity: 0.9,
      activeWordBgColor: 'rgba(224, 36, 255, 0.25)',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(224, 36, 255, 0.7)',
      shadowBlur: 18,
      shadowOffsetY: 0,
      animationType: 'neon_glow',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
    },
  },
  {
    id: 'golden_luxe_aura',
    name: '🌟 Golden Luxe',
    platform: 'instagram_reels',
    description: 'Premium gold metallic text with rich subtle shadow for luxury content.',
    style: {
      fontFamily: 'Cinzel, serif',
      fontSize: 46,
      activeWordColor: '#FFD700', // Gold
      inactiveWordColor: '#F1F5F9',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 12, 5, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(255, 215, 0, 0.4)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'bounce',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 72,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'volcano_orange_pop',
    name: '🌋 Volcano Orange',
    platform: 'tiktok',
    description: 'Fiery orange and bright yellow pop scale for high energy storytelling.',
    style: {
      fontFamily: 'Bungee, Impact, sans-serif',
      fontSize: 48,
      activeWordColor: '#FF6B00', // Flame Orange
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.8)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 107, 0, 0.5)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'pop',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
    },
  },
  {
    id: 'minimal_clean_white',
    name: '⚪ Clean Minimalist',
    platform: 'custom',
    description: 'Sleek white text with subtle underline and active word pulse.',
    style: {
      fontFamily: 'Urbanist, "Space Grotesk", sans-serif',
      fontSize: 44,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#94A3B8',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 6,
      shadowOffsetY: 2,
      animationType: 'minimal',
      maxWordsPerLine: 4,
      textTransform: 'none',
      positionYPercent: 80,
      positionXPercent: 50,
      emojiEnabled: false,
      autoEmojiKeywords: false,
      activeScaleFactor: 1.08,
    },
  },
  {
    id: 'dark_stealth_amber',
    name: '🖤 Dark Stealth Amber',
    platform: 'custom',
    description: 'Matte dark pill container with warm amber highlight.',
    style: {
      fontFamily: 'Syne, Montserrat, sans-serif',
      fontSize: 46,
      activeWordColor: '#F59E0B', // Amber
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: '#0F172A',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 8,
      shadowOffsetY: 2,
      animationType: 'bento_box',
      maxWordsPerLine: 3,
      textTransform: 'none',
      positionYPercent: 75,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.1,
    },
  },
  {
    id: 'cyber_glitch_chroma',
    name: '👾 Cyber Glitch',
    platform: 'tiktok',
    description: 'RGB chromatic aberration with high-tech jitter for futuristic edits.',
    style: {
      fontFamily: 'Audiowide, "Chakra Petch", sans-serif',
      fontSize: 50,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#F1F5F9',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 15, 26, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 240, 255, 0.8)',
      shadowBlur: 14,
      shadowOffsetY: 0,
      animationType: 'glitch',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'kinetic_slide_ascent',
    name: '🚀 Kinetic Slide Up',
    platform: 'youtube_shorts',
    description: 'Smooth spring float and upward slide as each spoken word drops in.',
    style: {
      fontFamily: '"Paytone One", sans-serif',
      fontSize: 48,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 10,
      shadowOffsetY: 3,
      animationType: 'slide_up',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'hype_impact_shake',
    name: '📳 Hype Tremor Punch',
    platform: 'tiktok',
    description: 'High-energy tremor vibration for punchlines, gaming kills, and shock hooks.',
    style: {
      fontFamily: '"Archivo Black", Anton, sans-serif',
      fontSize: 54,
      activeWordColor: '#FF2E4D',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 46, 77, 0.6)',
      shadowBlur: 16,
      shadowOffsetY: 4,
      animationType: 'shake',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 65,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
    },
  },
  {
    id: 'typewriter_noir_doc',
    name: '⌨️ Typewriter Noir',
    platform: 'custom',
    description: 'Live character-by-character speech reveal for storytelling and documentaries.',
    style: {
      fontFamily: '"Space Grotesk", monospace',
      fontSize: 44,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#94A3B8',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 23, 42, 0.95)',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 2,
      shadowColor: 'rgba(0,0,0,0.7)',
      shadowBlur: 8,
      shadowOffsetY: 2,
      animationType: 'typewriter',
      maxWordsPerLine: 4,
      textTransform: 'none',
      positionYPercent: 75,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.08,
    },
  },
  {
    id: 'ocean_harmonic_wave',
    name: '🌊 Harmonic Wave Float',
    platform: 'instagram_reels',
    description: 'Continuous sinusoidal wave floating motion across rhythmic captions.',
    style: {
      fontFamily: 'Fredoka, sans-serif',
      fontSize: 48,
      activeWordColor: '#38BDF8',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: 'rgba(3, 7, 18, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(56, 189, 248, 0.4)',
      shadowBlur: 12,
      shadowOffsetY: 2,
      animationType: 'wave',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'classic_pulse_bounce',
    name: '💓 Pulse Bounce Classic',
    platform: 'tiktok',
    description: 'The beloved classic scale-based sine pulse bounce on active words.',
    style: {
      fontFamily: '"League Spartan", Montserrat, sans-serif',
      fontSize: 52,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 10,
      shadowOffsetY: 3,
      animationType: 'bounce_pulse',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'jelly_rubber_band',
    name: '🪀 Jelly Rubber Band',
    platform: 'youtube_shorts',
    description: 'Elastic jelly stretch and rebound on speech impact.',
    style: {
      fontFamily: 'Kanit, sans-serif',
      fontSize: 52,
      activeWordColor: '#22C55E',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 46, 22, 0.9)',
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(34, 197, 94, 0.5)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'rubber_band',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'rainbow_spectrum_wave',
    name: '🌈 Spectrum Rainbow Wave',
    platform: 'tiktok',
    description: 'Hyper-vibrant rotating chromatic hue cycling across active words.',
    style: {
      fontFamily: '"Permanent Marker", cursive',
      fontSize: 48,
      activeWordColor: '#FF007F',
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 23, 42, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(255, 0, 127, 0.6)',
      shadowBlur: 16,
      shadowOffsetY: 3,
      animationType: 'color_cycle',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
    },
  },
  {
    id: 'spin_drop_kinetic',
    name: '💫 360 Spin Drop Snap',
    platform: 'instagram_reels',
    description: 'High-octane 360 spin drop with instant snap lock.',
    style: {
      fontFamily: 'Staatliches, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#F59E0B',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(245, 158, 11, 0.6)',
      shadowBlur: 14,
      shadowOffsetY: 3,
      animationType: 'spin_in',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 65,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'ali_abdaal_marker',
    name: '🖍️ Ali Abdaal Highlighter',
    platform: 'youtube_shorts',
    description: 'Authentic yellow felt-tip marker sweep across spoken words for educational authority.',
    style: {
      fontFamily: '"Plus Jakarta Sans", sans-serif',
      fontSize: 46,
      activeWordColor: '#111827',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: 'rgba(0, 0, 0, 0.7)',
      shadowBlur: 10,
      shadowOffsetY: 2,
      animationType: 'marker_highlight',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 72,
      positionXPercent: 50,
      emojiEnabled: false,
      autoEmojiKeywords: false,
      activeScaleFactor: 1.05,
    },
  },
  {
    id: 'iman_gadzhi_luxury',
    name: '✨ Iman Luxe Gold Glint',
    platform: 'instagram_reels',
    description: 'High-ticket luxury aesthetic with golden metallic specular luster sheen sweep.',
    style: {
      fontFamily: 'Cinzel, "Playfair Display", serif',
      fontSize: 48,
      activeWordColor: '#FFE57F',
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 10, 15, 0.85)',
      backgroundOpacity: 0.85,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(255, 215, 0, 0.5)',
      shadowBlur: 18,
      shadowOffsetY: 2,
      animationType: 'luxury_shimmer',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'beast_explosive_burst',
    name: '💥 Beast Shockwave Burst',
    platform: 'youtube_shorts',
    description: 'High-energy explosive punch with radial shockwave ring and particle rays.',
    style: {
      fontFamily: 'Impact, Anton, sans-serif',
      fontSize: 56,
      activeWordColor: '#FFCC00',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: '#000000',
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 204, 0, 0.8)',
      shadowBlur: 20,
      shadowOffsetY: 4,
      animationType: 'explosive_burst',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 66,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
    },
  },
  {
    id: 'cyber_matrix_hologram',
    name: '🛸 Matrix Hologram HUD',
    platform: 'tiktok',
    description: 'Futuristic sci-fi laser scanline sweep with cyan cyan glow & corner reticle accents.',
    style: {
      fontFamily: '"Share Tech Mono", monospace',
      fontSize: 46,
      activeWordColor: '#00FFCC',
      inactiveWordColor: '#94A3B8',
      useBackgroundPill: true,
      backgroundColor: 'rgba(2, 6, 23, 0.95)',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(0, 255, 204, 0.8)',
      shadowBlur: 22,
      shadowOffsetY: 0,
      animationType: 'hologram_scan',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: false,
      autoEmojiKeywords: false,
      activeScaleFactor: 1.15,
    },
  },
  {
    id: 'volcano_fire_blaze',
    name: '🔥 Volcano Fire Blaze',
    platform: 'tiktok',
    description: 'Hot ember flame gradient with organic heat shimmer vibration.',
    style: {
      fontFamily: '"Rubik Dirt", "Black Han Sans", sans-serif',
      fontSize: 54,
      activeWordColor: '#FF4500',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(20, 5, 0, 0.9)',
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 69, 0, 0.8)',
      shadowBlur: 24,
      shadowOffsetY: 3,
      animationType: 'fire_blaze',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
    },
  },
  {
    id: 'comic_pow_pop',
    name: '🗯️ Pop-Art Comic POW',
    platform: 'tiktok',
    description: 'Classic Marvel/DC comic book starburst badge with bold cartoon punch.',
    style: {
      fontFamily: '"Bangers", cursive',
      fontSize: 56,
      activeWordColor: '#000000',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 0, 0, 0.8)',
      shadowBlur: 10,
      shadowOffsetY: 4,
      animationType: 'comic_burst',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 65,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
    },
  },
  {
    id: 'aurora_cosmic_flow',
    name: '🌌 Aurora Borealis Flow',
    platform: 'instagram_reels',
    description: 'Ethereal multi-stop Northern Lights gradient with cosmic dream aura.',
    style: {
      fontFamily: 'Outfit, sans-serif',
      fontSize: 50,
      activeWordColor: '#00FFA3',
      inactiveWordColor: '#E0E7FF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(8, 7, 26, 0.88)',
      backgroundOpacity: 0.88,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: 'rgba(0, 255, 163, 0.6)',
      shadowBlur: 20,
      shadowOffsetY: 2,
      animationType: 'aurora_flow',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: false,
      autoEmojiKeywords: false,
      activeScaleFactor: 1.18,
    },
  },
  {
    id: 'plasma_high_voltage',
    name: '⚡ Plasma Arc High-Voltage',
    platform: 'tiktok',
    description: 'Electrifying branching lightning arcs and neon blue sparks with jitter.',
    style: {
      fontFamily: '"Chakra Petch", sans-serif',
      fontSize: 54,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: 'rgba(3, 7, 18, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 240, 255, 0.85)',
      shadowBlur: 24,
      shadowOffsetY: 0,
      animationType: 'electric_plasma',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'confetti_celebration_pop',
    name: '🎉 Confetti Celebration',
    platform: 'tiktok',
    description: 'Explosive 3D tumbling celebration confetti with joyful bounce.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 52,
      activeWordColor: '#FFD700',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 23, 42, 0.9)',
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(245, 158, 11, 0.7)',
      shadowBlur: 16,
      shadowOffsetY: 3,
      animationType: 'confetti_party',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      particleFxEnabled: true,
    },
  },
  {
    id: 'golden_cash_vip',
    name: '💰 24K Golden Cash & Coins',
    platform: 'youtube_shorts',
    description: 'Luxury metallic gold gradient fill with floating 3D rotating gold coins.',
    style: {
      fontFamily: '"Cinzel", "Times New Roman", serif',
      fontSize: 50,
      activeWordColor: '#FFD700',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 10, 10, 0.94)',
      backgroundOpacity: 0.94,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(255, 215, 0, 0.75)',
      shadowBlur: 20,
      shadowOffsetY: 3,
      animationType: 'golden_cash',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.3,
      particleFxEnabled: true,
    },
  },
  {
    id: 'molten_lava_surge',
    name: '🌋 Molten Lava Surge',
    platform: 'tiktok',
    description: 'Animated volcanic wave gradient with buoyant floating magma orbs.',
    style: {
      fontFamily: '"Rubik", sans-serif',
      fontSize: 54,
      activeWordColor: '#FF5500',
      inactiveWordColor: '#FFE4E6',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 5, 5, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 69, 0, 0.8)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'liquid_lava',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.2,
      particleFxEnabled: true,
    },
  },
  {
    id: 'rgb_glitch_cyberpunk',
    name: '👾 Cyberpunk RGB Glitch',
    platform: 'tiktok',
    description: 'Multi-channel chromatic aberration displacement with laser scanlines.',
    style: {
      fontFamily: '"Space Grotesk", monospace',
      fontSize: 52,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#94A3B8',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 5, 10, 0.95)',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 240, 255, 0.7)',
      shadowBlur: 18,
      shadowOffsetY: 0,
      animationType: 'rgb_split_glitch',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: false,
      autoEmojiKeywords: false,
      activeScaleFactor: 1.18,
    },
  },
  {
    id: 'vip_crown_luxury',
    name: '👑 Royal Crown Halo',
    platform: 'instagram_reels',
    description: 'Floating golden VIP crown badge with sparkling glints and gold fill.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 52,
      activeWordColor: '#F59E0B',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 23, 42, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(245, 158, 11, 0.7)',
      shadowBlur: 18,
      shadowOffsetY: 3,
      animationType: 'crown_halo',
      maxWordsPerLine: 2,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      particleFxEnabled: true,
    },
  },
  {
    id: 'meteor_strike_beast',
    name: '☄️ Meteor Ground Slam',
    platform: 'tiktok',
    description: 'Devastating fiery asteroid impact with expanding seismic crater cracks and molten rock sparks.',
    style: {
      fontFamily: 'Impact, "Bebas Neue", sans-serif',
      fontSize: 56,
      activeWordColor: '#FF4500',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 5, 5, 0.94)',
      backgroundOpacity: 0.94,
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 69, 0, 0.85)',
      shadowBlur: 24,
      shadowOffsetY: 3,
      animationType: 'meteor_impact',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'cyber_katana_neon',
    name: '⚔️ Cyber Katana Slash',
    platform: 'youtube_shorts',
    description: 'Dual intersecting anime energy blade slashes with hot white core and chromatic sparks.',
    style: {
      fontFamily: '"Chakra Petch", sans-serif',
      fontSize: 54,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 5, 16, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 240, 255, 0.8)',
      shadowBlur: 22,
      shadowOffsetY: 0,
      animationType: 'cyber_katana_slash',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.3,
      particleFxEnabled: true,
    },
  },
  {
    id: 'diamond_crystal_luxe',
    name: '💎 Diamond Crystal Shatter',
    platform: 'instagram_reels',
    description: 'Faceted 3D prismatic crystal reflection with flying glass shards and rainbow glints.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 52,
      activeWordColor: '#E0F7FA',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 15, 29, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(128, 222, 234, 0.8)',
      shadowBlur: 20,
      shadowOffsetY: 2,
      animationType: 'diamond_shatter',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.24,
      glowIntensity: 1.25,
      particleFxEnabled: true,
    },
  },
  {
    id: 'matrix_rain_hacker',
    name: '🟢 Matrix Digital Rain',
    platform: 'tiktok',
    description: 'Cascading vertical Matrix code stream columns with glowing neon green terminals.',
    style: {
      fontFamily: '"Space Grotesk", monospace',
      fontSize: 52,
      activeWordColor: '#39FF14',
      inactiveWordColor: '#94A3B8',
      useBackgroundPill: true,
      backgroundColor: 'rgba(2, 8, 4, 0.95)',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(57, 255, 20, 0.8)',
      shadowBlur: 18,
      shadowOffsetY: 0,
      animationType: 'matrix_digital_rain',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: false,
      autoEmojiKeywords: false,
      activeScaleFactor: 1.18,
      glowIntensity: 1.2,
      particleFxEnabled: true,
    },
  },
  {
    id: 'quantum_portal_wormhole',
    name: '🌌 Quantum Portal Vortex',
    platform: 'youtube_shorts',
    description: 'Swirling deep space cosmic wormhole disk with spinning gravitational spiral arms.',
    style: {
      fontFamily: '"Orbitron", sans-serif',
      fontSize: 52,
      activeWordColor: '#C084FC',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 10, 30, 0.94)',
      backgroundOpacity: 0.94,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(168, 85, 247, 0.85)',
      shadowBlur: 24,
      shadowOffsetY: 0,
      animationType: 'quantum_portal',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.3,
      particleFxEnabled: true,
    },
  },
  {
    id: 'pop_art_comic_pow',
    name: '🗯️ Pop-Art Action POW',
    platform: 'tiktok',
    description: 'Roy Lichtenstein comic book halftone dot matrix with black action rays and bold ink.',
    style: {
      fontFamily: 'Impact, "Bebas Neue", sans-serif',
      fontSize: 56,
      activeWordColor: '#000000',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#FFFFFF',
      strokeWidth: 2,
      shadowColor: 'rgba(0, 0, 0, 0.8)',
      shadowBlur: 8,
      shadowOffsetY: 4,
      animationType: 'pop_art_dot_matrix',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      activeWordBgColor: '#FFE600',
    },
  },
  {
    id: 'radioactive_biohazard',
    name: '☣️ Toxic Biohazard Pulse',
    platform: 'tiktok',
    description: 'Radioactive neon green hazard pulse ring with rising fizzing toxic slime bubbles.',
    style: {
      fontFamily: '"Rubik", sans-serif',
      fontSize: 54,
      activeWordColor: '#39FF14',
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 15, 5, 0.94)',
      backgroundOpacity: 0.94,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(57, 255, 20, 0.85)',
      shadowBlur: 22,
      shadowOffsetY: 0,
      animationType: 'radioactive_toxic',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'hyper_drive_interstellar',
    name: '🚀 Interstellar Hyper-Drive',
    platform: 'youtube_shorts',
    description: 'Light-speed hyperspace star streaks radiating outwards with radial velocity snap.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 54,
      activeWordColor: '#38BDF8',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(2, 6, 23, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(56, 189, 248, 0.8)',
      shadowBlur: 20,
      shadowOffsetY: 0,
      animationType: 'hyper_drive_warp',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.25,
      particleFxEnabled: true,
    },
  },
  {
    id: 'graffiti_street_artist',
    name: '🎨 Urban Street Graffiti',
    platform: 'tiktok',
    description: 'Aerosol spray paint mist cloud backdrop with realistic dripping paint runs.',
    style: {
      fontFamily: 'Impact, "Bebas Neue", sans-serif',
      fontSize: 54,
      activeWordColor: '#F43F5E',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(244, 63, 94, 0.7)',
      shadowBlur: 16,
      shadowOffsetY: 3,
      animationType: 'graffiti_spray',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      activeWordBgColor: '#F43F5E',
    },
  },
  {
    id: 'neon_wireframe_3d_cube',
    name: '🧊 3D Isometric Neon Cube',
    platform: 'instagram_reels',
    description: 'Rotating 3D cyber wireframe perspective cage with glowing corner vertices.',
    style: {
      fontFamily: '"Chakra Petch", sans-serif',
      fontSize: 52,
      activeWordColor: '#38BDF8',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(8, 15, 30, 0.94)',
      backgroundOpacity: 0.94,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(56, 189, 248, 0.8)',
      shadowBlur: 20,
      shadowOffsetY: 0,
      animationType: 'neon_wireframe_3d',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.3,
    },
  },
  {
    id: 'thunder_god_strike',
    name: '⚡ Thor Thunder Strike',
    platform: 'tiktok',
    description: 'Descending high-voltage lightning bolts striking down with branching electric forks.',
    style: {
      fontFamily: 'Impact, "Bebas Neue", sans-serif',
      fontSize: 56,
      activeWordColor: '#38BDF8',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.88)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(56, 189, 248, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 3,
      animationType: 'thunder_god_lightning',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'firework_celebration_finale',
    name: '🎆 Fireworks Grand Finale',
    platform: 'youtube_shorts',
    description: 'Pyrotechnic aerial fireworks bursting into multicolored glittering star trails.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 5, 25, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 230, 0, 0.85)',
      shadowBlur: 20,
      shadowOffsetY: 2,
      animationType: 'firework_grand_finale',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.3,
      particleFxEnabled: true,
    },
  },
  {
    id: 'super_saiyan_ki_power',
    name: '🔥 Super Saiyan Ki Flame',
    platform: 'tiktok',
    description: 'Billowing anime Ki plasma flame plumes rising around text with rising electric sparks.',
    style: {
      fontFamily: '"Bebas Neue", Impact, sans-serif',
      fontSize: 56,
      activeWordColor: '#FFF500',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 230, 0, 0.95)',
      shadowBlur: 25,
      shadowOffsetY: 2,
      animationType: 'super_saiyan_aura',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.26,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'vhs_glitch_retro_80s',
    name: '📼 80s VHS Glitch & Tape',
    platform: 'instagram_reels',
    description: 'Retro analog VHS tracking scanlines, chromatic RGB color shifts, and static grain.',
    style: {
      fontFamily: '"Courier Prime", monospace',
      fontSize: 50,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 5, 10, 0.95)',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 240, 255, 0.8)',
      shadowBlur: 16,
      shadowOffsetY: 0,
      animationType: 'glitch_vhs_tape',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.15,
      glowIntensity: 1.2,
    },
  },
  {
    id: 'solar_eclipse_corona',
    name: '☀️ Solar Eclipse Corona',
    platform: 'youtube_shorts',
    description: 'Blinding astronomical solar corona flare around text with coronal mass plasma loops.',
    style: {
      fontFamily: '"Montserrat", sans-serif',
      fontSize: 52,
      activeWordColor: '#FFFBEB',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 69, 0, 0.9)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'solar_flare_corona',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'synthwave_outrun_grid',
    name: '🌆 80s Synthwave Sunset Grid',
    platform: 'tiktok',
    description: '3D perspective wireframe horizon grid beneath word with setting retro neon striped sun.',
    style: {
      fontFamily: '"Russo One", sans-serif',
      fontSize: 52,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 5, 25, 0.95)',
      backgroundOpacity: 0.95,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 0, 127, 0.85)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'synthwave_retro_grid',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 68,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.35,
    },
  },
  {
    id: 'phoenix_fire_rebirth',
    name: '🦅 Phoenix Flame Wings',
    platform: 'youtube_shorts',
    description: 'Radiant sweeping fire wing silhouettes extending outward with buoyant embers.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 69, 0, 0.9)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'golden_fire_phoenix',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.24,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'crystal_prism_caustics',
    name: '💎 Prismatic Rainbow Diamond',
    platform: 'instagram_reels',
    description: 'Crystalline light caustics refracting dynamic iridescent spectrum caustics and diamond twinkles.',
    style: {
      fontFamily: '"Playfair Display", serif',
      fontSize: 52,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 15, 25, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 240, 255, 0.85)',
      shadowBlur: 20,
      shadowOffsetY: 2,
      animationType: 'crystal_prismatic_rainbow',
      maxWordsPerLine: 2,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.18,
      glowIntensity: 1.3,
      particleFxEnabled: true,
    },
  },
  {
    id: 'shonen_manga_speed_frame',
    name: '💥 Shonen Manga Speed Lines',
    platform: 'tiktok',
    description: 'Classic anime manga impact frame with radiating black/white action speed lines and high-tension shake.',
    style: {
      fontFamily: 'Impact, "Bebas Neue", sans-serif',
      fontSize: 56,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.9)',
      strokeColor: '#000000',
      strokeWidth: 7,
      shadowColor: 'rgba(0, 0, 0, 0.95)',
      shadowBlur: 14,
      shadowOffsetY: 4,
      animationType: 'kinetic_speed_lines_impact',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
    },
  },
  {
    id: 'mystic_runic_sorcerer',
    name: '🔮 Mystic Arcane Spell Circle',
    platform: 'youtube_shorts',
    description: 'Doctor Strange glowing spinning geometric arcane spell mandala rings with glowing runes.',
    style: {
      fontFamily: '"Cinzel", serif',
      fontSize: 52,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 102, 0, 0.9)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'magic_runic_circle',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'black_hole_event_horizon',
    name: '🌌 Cosmic Singularity & Photon Ring',
    platform: 'tiktok',
    description: 'Gravitational event horizon with rotating plasma accretion disk and photon ring beaming.',
    style: {
      fontFamily: '"Montserrat", Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#F1F5F9',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.92)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'black_hole_singularity',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'divine_celestial_god_rays',
    name: '✨ Celestial God Rays & Holy Aura',
    platform: 'youtube_shorts',
    description: 'Volumetric heavenly light shafts streaming down through text with floating golden dust motes.',
    style: {
      fontFamily: '"Cinzel", "Playfair Display", serif',
      fontSize: 52,
      activeWordColor: '#FFFDF0',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 230, 100, 0.95)',
      shadowBlur: 25,
      shadowOffsetY: 2,
      animationType: 'god_rays_divine',
      maxWordsPerLine: 2,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'cyberpunk_mecha_targeting_hud',
    name: '🤖 Cyberpunk HUD & Combat Lock',
    platform: 'tiktok',
    description: 'Sci-fi military brackets, rotating compass dial, and telemetry target acquisition locking.',
    style: {
      fontFamily: '"Share Tech Mono", monospace',
      fontSize: 50,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#E0F2FE',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 10, 20, 0.94)',
      backgroundOpacity: 0.94,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 240, 255, 0.9)',
      shadowBlur: 20,
      shadowOffsetY: 0,
      animationType: 'cyberpunk_hud_matrix',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.18,
      glowIntensity: 1.35,
    },
  },
  {
    id: 'subzero_cryo_blizzard',
    name: '❄️ Sub-Zero Glacial Ice Spikes',
    platform: 'instagram_reels',
    description: 'Sharp cryo ice crystal stalagmites bursting outward with glacial blue frost mist.',
    style: {
      fontFamily: 'Impact, "Bebas Neue", sans-serif',
      fontSize: 54,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#F0F9FF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.88)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(56, 189, 248, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'ice_blizzard_frost',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'toxic_acid_neon_graffiti',
    name: '🧪 Radioactive Toxic Acid Splatter',
    platform: 'tiktok',
    description: 'High-energy radioactive paint blast with realistic dripping paint runs and neon pink flecks.',
    style: {
      fontFamily: '"Permanent Marker", "Bebas Neue", cursive',
      fontSize: 54,
      activeWordColor: '#39FF14',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(57, 255, 20, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 3,
      animationType: 'neon_graffiti_drip',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'dragon_fire_inferno_vortex',
    name: '🐉 Dragon Breath Flame Vortex',
    platform: 'youtube_shorts',
    description: 'Scorching dual-stream dragon plasma vortex wrapping around text with floating fire sparks.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 56,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 69, 0, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'dragon_breath_inferno',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.26,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'royal_24k_gold_trophy',
    name: '🏆 24K Liquid Gold Trophy Sheen',
    platform: 'instagram_reels',
    description: 'Ultra-luxurious 24K liquid gold chrome gradient with sweeping specular light sheen and orbit stars.',
    style: {
      fontFamily: '"Montserrat", sans-serif',
      fontSize: 52,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(15, 10, 5, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 215, 0, 0.9)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'golden_trophy_shimmer',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'speed_demon_hyper_drift',
    name: '🏎️ Nitro Drift & Speed Streaks',
    platform: 'tiktok',
    description: 'Flaming tire skid trails, dual cyan turbo jet fire bursts, and kinetic racing drift tilt.',
    style: {
      fontFamily: 'Impact, "Bebas Neue", sans-serif',
      fontSize: 54,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 240, 255, 0.9)',
      shadowBlur: 20,
      shadowOffsetY: 2,
      animationType: 'speed_demon_drift',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.35,
    },
  },
  {
    id: 'pop_comic_pow_action',
    name: '💥 3D Comic Action Starburst',
    platform: 'tiktok',
    description: 'Explosive 3D pop-art yellow starburst badge with black ink contours and action halftone dots.',
    style: {
      fontFamily: '"Bangers", Impact, cursive',
      fontSize: 56,
      activeWordColor: '#000000',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#FFFFFF',
      strokeWidth: 0,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 12,
      shadowOffsetY: 4,
      animationType: 'comic_action_blast_bubble',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
    },
  },
  {
    id: 'quantum_entanglement_orbit',
    name: '⚛️ Quantum Particle Strings & Orbit',
    platform: 'youtube_shorts',
    description: 'Intersecting 3-axis orbital electron rings spinning with quantum probability waves.',
    style: {
      fontFamily: '"Russo One", sans-serif',
      fontSize: 52,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(5, 5, 20, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'quantum_entanglement_strings',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'iron_arc_reactor_core',
    name: '⚡ Arc Reactor Plasma Unibeam',
    platform: 'tiktok',
    description: 'Concentric magnetic containment coils, counter-rotating reactor rings, and blinding unibeam flare.',
    style: {
      fontFamily: '"Montserrat", Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.92)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 26,
      shadowOffsetY: 2,
      animationType: 'plasma_arc_reactor',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'cyber_hex_matrix_portal',
    name: '🌐 Cyber Hex Matrix Portal & Glitch',
    platform: 'tiktok',
    description: 'Hexagonal honeycomb energy shield grid with pulsing active data nodes and chromatic glitch slices.',
    style: {
      fontFamily: '"Share Tech Mono", monospace',
      fontSize: 52,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: true,
      backgroundColor: 'rgba(5, 5, 25, 0.94)',
      backgroundOpacity: 0.94,
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(255, 0, 128, 0.9)',
      shadowBlur: 22,
      shadowOffsetY: 0,
      animationType: 'matrix_cyber_glitch_portal',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'anime_water_wheel_dragon',
    name: '🌊 Anime Hydro Blade & Dragon Waves',
    platform: 'youtube_shorts',
    description: 'Japanese woodblock Ukiyo-e wave curves curling around text with water droplet splash bursts.',
    style: {
      fontFamily: '"Bebas Neue", Anton, sans-serif',
      fontSize: 56,
      activeWordColor: '#67E8F9',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#001A4D',
      strokeWidth: 6,
      shadowColor: 'rgba(56, 189, 248, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 3,
      animationType: 'demon_slayer_water_wheel',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.24,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'andromeda_galaxy_nebula',
    name: '🪐 Andromeda Nebula & Ringed Exoplanet',
    platform: 'instagram_reels',
    description: 'Multi-layer glowing cosmic gas nebula clouds with orbiting ringed exoplanet and stellar clusters.',
    style: {
      fontFamily: '"Montserrat", sans-serif',
      fontSize: 52,
      activeWordColor: '#E879F9',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: false,
      backgroundColor: 'rgba(5, 2, 15, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(192, 132, 252, 0.95)',
      shadowBlur: 25,
      shadowOffsetY: 2,
      animationType: 'galaxy_nebula_supercluster',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'cyber_ninja_shuriken_storm',
    name: '🥷 Cyber Ninja Laser Shuriken',
    platform: 'tiktok',
    description: 'Dual spinning 4-blade neon laser shurikens slicing with supersonic kinetic speed trails.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.92)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'neon_cyber_shuriken',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.26,
      glowIntensity: 1.45,
    },
  },
  {
    id: 'tesla_coil_lightning_discharge',
    name: '⚡ Tesla Coil High-Frequency Chain Arc',
    platform: 'youtube_shorts',
    description: 'Dual Tesla coil spheres generating intense continuous branching high-voltage violet plasma arcs.',
    style: {
      fontFamily: '"Montserrat", Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#E879F9',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(192, 132, 252, 0.95)',
      shadowBlur: 25,
      shadowOffsetY: 2,
      animationType: 'lightning_chain_tesla',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'sakura_samurai_katana_slash',
    name: '🌸 Sakura Samurai Katana & Petal Vortex',
    platform: 'instagram_reels',
    description: 'Clean razor katana slash gleam cutting through center with fluttering cherry blossom petals.',
    style: {
      fontFamily: '"Cinzel", "Playfair Display", serif',
      fontSize: 52,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#FDF2F8',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.85)',
      strokeColor: '#831843',
      strokeWidth: 4,
      shadowColor: 'rgba(244, 114, 182, 0.95)',
      shadowBlur: 20,
      shadowOffsetY: 2,
      animationType: 'cherry_blossom_samurai_slash',
      maxWordsPerLine: 2,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'liquid_mercury_metal_morph',
    name: '🪞 T-1000 Liquid Chrome Mercury Morph',
    platform: 'youtube_shorts',
    description: 'Specular liquid metallic reflection waves morphing across text with dripping mercury globules.',
    style: {
      fontFamily: '"Montserrat", sans-serif',
      fontSize: 54,
      activeWordColor: '#FFFFFF',
      inactiveWordColor: '#CBD5E1',
      useBackgroundPill: true,
      backgroundColor: 'rgba(10, 15, 25, 0.92)',
      backgroundOpacity: 0.92,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(226, 232, 240, 0.9)',
      shadowBlur: 20,
      shadowOffsetY: 2,
      animationType: 'liquid_mercury_chrome',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.18,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'zodiac_astral_constellation',
    name: '✨ Zodiac Astral Constellation & Sacred Stars',
    platform: 'instagram_reels',
    description: 'Luminous star nodes connected by pulsing laser filament lines and sacred geometric astral rings.',
    style: {
      fontFamily: '"Cinzel", "Playfair Display", serif',
      fontSize: 52,
      activeWordColor: '#FDE047',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(5, 5, 20, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(221, 214, 254, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'astral_constellation_zodiac',
      maxWordsPerLine: 2,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'volcano_magma_obsidian_burst',
    name: '🌋 Volcanic Magma Eruption & Obsidian Shards',
    platform: 'tiktok',
    description: 'Glowing molten magma trench fissure with exploding obsidian rock shards and fiery ember sparks.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 56,
      activeWordColor: '#FDE047',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0,0,0,0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 69, 0, 0.95)',
      shadowBlur: 26,
      shadowOffsetY: 3,
      animationType: 'lava_magma_eruption',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'sci_fi_hologram_matrix_teleport',
    name: '🌐 Hologram Matrix Teleport & Digital Reconstruction',
    platform: 'tiktok',
    description: 'Sci-Fi laser plane scanbeam, floating hexadecimal matrix telemetry, and corner HUD reticle brackets.',
    style: {
      fontFamily: 'Orbitron, sans-serif',
      fontSize: 52,
      activeWordColor: '#00FFCC',
      inactiveWordColor: '#E0F2FE',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0, 10, 20, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'hologram_matrix_teleport',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'cursed_black_flame_amaterasu',
    name: '🖤 Cursed Black Flame Inferno & Purple Soul Embers',
    platform: 'tiktok',
    description: 'Mythic swirling jet-black dark matter flames edged with violet-magenta plasma spikes and rising soul wisps.',
    style: {
      fontFamily: '"Black Han Sans", Impact, sans-serif',
      fontSize: 56,
      activeWordColor: '#F472B6',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(5, 0, 10, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(192, 38, 211, 0.95)',
      shadowBlur: 26,
      shadowOffsetY: 3,
      animationType: 'vortex_black_flame_amaterasu',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'celestial_supernova_detonation',
    name: '💥 Supernova Cosmic Detonation & Shockwave',
    platform: 'youtube_shorts',
    description: 'Celestial thermonuclear core pulse, relativistic circular shockwave rings, and 4-point starburst flare spikes.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 54,
      activeWordColor: '#FEF08A',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(10, 5, 0, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 215, 0, 0.95)',
      shadowBlur: 28,
      shadowOffsetY: 2,
      animationType: 'supernova_cosmic_shockwave',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
      glowIntensity: 1.6,
      particleFxEnabled: true,
    },
  },
  {
    id: 'japanese_kintsugi_gold_fracture',
    name: '🏺 Kintsugi Golden Crack Repair & Shimmer Seams',
    platform: 'instagram_reels',
    description: 'Branching 24K molten gold fracture seams across text with sweeping specular shine and floating gold leaf flakes.',
    style: {
      fontFamily: '"Cinzel", "Playfair Display", serif',
      fontSize: 50,
      activeWordColor: '#FBBF24',
      inactiveWordColor: '#F8FAFC',
      useBackgroundPill: false,
      backgroundColor: 'rgba(15, 10, 5, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(255, 215, 0, 0.9)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'golden_kintsugi_fracture',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'synthwave_laser_highway_outrun',
    name: '🏎️ Synthwave Neon Grid Highway & Digital Sun',
    platform: 'tiktok',
    description: '3D perspective receding neon road grid with outrun wireframe sun horizon and magenta/cyan laser trails.',
    style: {
      fontFamily: 'Orbitron, sans-serif',
      fontSize: 52,
      activeWordColor: '#FF007F',
      inactiveWordColor: '#E2E8F0',
      useBackgroundPill: false,
      backgroundColor: 'rgba(10, 2, 20, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(255, 0, 127, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'hyper_synth_laser_highway',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.26,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'cyber_neuro_glitch_overload',
    name: '⚡ Cyberpunk Neuro Glitch Overload & Data Slices',
    platform: 'tiktok',
    description: 'Dynamic chromatic RGB split shift with horizontal pixel circuit slices, error flags, and jitter twitch displacement.',
    style: {
      fontFamily: 'Orbitron, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#00F0FF',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(5, 5, 10, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'cyber_glitch_overload_rgb',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'nordic_emerald_aurora_sky',
    name: '🌌 Nordic Emerald Aurora Sky & Stardust Waves',
    platform: 'instagram_reels',
    description: 'Serpentine flowing emerald-cyan northern light ribbons undulating smoothly with sparkling arctic stardust.',
    style: {
      fontFamily: '"Montserrat", "Plus Jakarta Sans", sans-serif',
      fontSize: 52,
      activeWordColor: '#A7F3D0',
      inactiveWordColor: '#F0FDFA',
      useBackgroundPill: false,
      backgroundColor: 'rgba(2, 15, 15, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(16, 185, 129, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'emerald_aurora_borealis_flow',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'shonen_spirit_bomb_ki_sphere',
    name: '🌀 Anime Spirit Energy Bomb & Ki Gathering Vortex',
    platform: 'tiktok',
    description: 'Hovering blue Spirit Bomb Ki sphere with inward-spiraling energy streams and radiating ionic shockwaves.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 56,
      activeWordColor: '#38BDF8',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0, 10, 25, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 28,
      shadowOffsetY: 2,
      animationType: 'shonen_energy_spirit_bomb',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'diamond_hyper_laser_disco_prism',
    name: '💎 Prismatic Diamond Caustics & Laser Prism Beams',
    platform: 'youtube_shorts',
    description: 'Multi-beam spectrum rainbow laser caustics with rotating 3D crystal gem stars and specular sheen sweep.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 52,
      activeWordColor: '#00FF9D',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(10, 0, 20, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 240, 255, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'diamond_hyper_disco_prism',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'phoenix_wings_solar_ascension_god',
    name: '🔥 Divine Solar Phoenix Wings & Golden Feathers',
    platform: 'tiktok',
    description: 'Majestic flaming golden phoenix wings stretching outward, shedding drifting burning feathers with solar halo.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 56,
      activeWordColor: '#FEF08A',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(15, 5, 0, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(255, 69, 0, 0.95)',
      shadowBlur: 28,
      shadowOffsetY: 3,
      animationType: 'phoenix_wings_solar_ascension',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'casino_jackpot_gold_777',
    name: '🎰 Vegas Gold 777 Jackpot & Marquee Bulbs',
    platform: 'tiktok',
    description: 'Vegas gold marquee frame with chasing bulbs, top 777 jackpot badge, and raining $ stamped 3D gold coins.',
    style: {
      fontFamily: 'Impact, "Black Han Sans", sans-serif',
      fontSize: 56,
      activeWordColor: '#FEF08A',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(20, 10, 0, 0.9)',
      strokeColor: '#78350F',
      strokeWidth: 5,
      shadowColor: 'rgba(245, 158, 11, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'casino_jackpot_gold_rush',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'neon_audio_eq_visualizer_spectrum',
    name: '🔊 Neon Audio EQ Visualizer & Spectrum Bars',
    platform: 'youtube_shorts',
    description: 'Dynamic 16-band audio spectrum equalizer bars dancing with peak hold caps and vibrant multi-frequency hues.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 52,
      activeWordColor: '#34D399',
      inactiveWordColor: '#F0FDFA',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0, 20, 25, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(6, 182, 212, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'audio_visualizer_eq_bars',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'retro_arcade_8bit_pixel_ko',
    name: '👾 8-Bit Retro Arcade Pixel KO & +1000 PTS',
    platform: 'tiktok',
    description: 'Chunky 8-bit CRT arcade border, stepped pixel corners, floating +1000 PTS score tag, and spinning pixel coin.',
    style: {
      fontFamily: '"Press Start 2P", monospace',
      fontSize: 42,
      activeWordColor: '#FFE600',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(5, 5, 10, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 255, 102, 0.95)',
      shadowBlur: 18,
      shadowOffsetY: 2,
      animationType: 'retro_arcade_8bit_gameover',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'toxic_nuclear_biohazard_caution_tape',
    name: '☣️ Nuclear Biohazard Caution Tape & Ooze',
    platform: 'tiktok',
    description: 'Animated diagonal black/yellow caution hazard stripes, rotating radioactive trefoil, and green ooze droplets.',
    style: {
      fontFamily: 'Anton, Impact, sans-serif',
      fontSize: 56,
      activeWordColor: '#86EFAC',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(10, 20, 5, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(34, 197, 94, 0.95)',
      shadowBlur: 26,
      shadowOffsetY: 2,
      animationType: 'toxic_nuclear_biohazard_tape',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'dimensional_hyperspace_rift_tear',
    name: '🌌 Dimensional Space Rift Tear & Cosmic Void',
    platform: 'youtube_shorts',
    description: 'Jagged dark matter reality fracture exposing purple hyperspace void, cosmic lightning, and inward gravitational pull.',
    style: {
      fontFamily: 'Orbitron, sans-serif',
      fontSize: 52,
      activeWordColor: '#E879F9',
      inactiveWordColor: '#FAF5FF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(15, 0, 30, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(192, 132, 252, 0.95)',
      shadowBlur: 26,
      shadowOffsetY: 2,
      animationType: 'dimensional_space_rift_tear',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'manga_screentone_impact_action_punch',
    name: '🗯️ Manga Screentone Impact & Action Kanji',
    platform: 'tiktok',
    description: 'High-contrast manga screentone speedlines, comic POW explosion burst, and red Japanese action Kanji [ドンッ!].',
    style: {
      fontFamily: '"Black Han Sans", Impact, sans-serif',
      fontSize: 58,
      activeWordColor: '#FCA5A5',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0, 0, 0, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 7,
      shadowColor: 'rgba(220, 38, 38, 0.95)',
      shadowBlur: 20,
      shadowOffsetY: 3,
      animationType: 'manga_screentone_comic_punch',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.35,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'matrix_falling_green_code_waterfall',
    name: '💻 Matrix Green Katakana Waterfall Cascade',
    platform: 'tiktok',
    description: '9 distinct columns of falling Japanese Katakana and binary code streams with glowing white leader characters.',
    style: {
      fontFamily: 'Orbitron, monospace',
      fontSize: 52,
      activeWordColor: '#86EFAC',
      inactiveWordColor: '#F0FDF4',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0, 15, 5, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 255, 102, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'matrix_falling_code_cascade',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'tactical_laser_sniper_target_lock_on',
    name: '🎯 Tactical Sniper Target Lock & Rangefinder',
    platform: 'youtube_shorts',
    description: 'Military sniper scope reticle with rotating compass ticks, clamping corner brackets, and red laser telemetry [LOCKED].',
    style: {
      fontFamily: 'Orbitron, sans-serif',
      fontSize: 52,
      activeWordColor: '#EF4444',
      inactiveWordColor: '#FEF2F2',
      useBackgroundPill: false,
      backgroundColor: 'rgba(20, 0, 0, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(239, 68, 68, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'laser_sniper_target_lock',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.26,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'magical_girl_prism_wand_starlight',
    name: '💖 Magical Girl Heart Wand & Starlight Sparkle',
    platform: 'instagram_reels',
    description: 'Spinning golden-pink crystal star wand crest, pastel rainbow ribbon arcs, and orbiting magical starlight glints.',
    style: {
      fontFamily: '"Montserrat", "Plus Jakarta Sans", sans-serif',
      fontSize: 52,
      activeWordColor: '#F472B6',
      inactiveWordColor: '#FFF1F2',
      useBackgroundPill: false,
      backgroundColor: 'rgba(25, 5, 20, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(244, 114, 182, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'magical_girl_prism_wand',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.25,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'cyberpunk_glitch_skull_cyber_reaper',
    name: '💀 Cyber Reaper Hologram Skull & Death Counter',
    platform: 'tiktok',
    description: 'Holographic glowing crimson cyber skull with laser eye sockets, telemetry death counter, and twitch glitch slices.',
    style: {
      fontFamily: 'Orbitron, Impact, sans-serif',
      fontSize: 54,
      activeWordColor: '#F87171',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(15, 0, 5, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(220, 38, 38, 0.95)',
      shadowBlur: 26,
      shadowOffsetY: 2,
      animationType: 'glitch_skull_cyber_reaper',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'vintage_polaroid_camera_flash',
    name: '📸 Vintage 90s Polaroid Instant Flash & Card',
    platform: 'instagram_reels',
    description: 'White Polaroid instant photo frame with signature rainbow strip and entrance flash burst effect.',
    style: {
      fontFamily: '"Caveat", "Playfair Display", cursive, serif',
      fontSize: 48,
      activeWordColor: '#F8FAFC',
      inactiveWordColor: '#CBD5E1',
      useBackgroundPill: false,
      backgroundColor: '#FFFFFF',
      strokeColor: '#0F172A',
      strokeWidth: 2,
      shadowColor: 'rgba(0, 0, 0, 0.5)',
      shadowBlur: 14,
      shadowOffsetY: 4,
      animationType: 'polaroid_instant_camera_flash',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.18,
      glowIntensity: 1.1,
      particleFxEnabled: true,
    },
  },
  {
    id: 'police_emergency_siren_red_blue',
    name: '🚨 911 Emergency Police Siren & Strobe Beacons',
    platform: 'tiktok',
    description: 'Alternating red and blue flashing emergency lightbars with high-speed strobe flares and shake.',
    style: {
      fontFamily: 'Impact, "Black Han Sans", sans-serif',
      fontSize: 56,
      activeWordColor: '#EF4444',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0, 0, 0, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(239, 68, 68, 0.95)',
      shadowBlur: 28,
      shadowOffsetY: 2,
      animationType: 'police_siren_strobe_cop',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'breaking_news_burning_paper_headline',
    name: '📰 Breaking News Burning Parchment Headline',
    platform: 'youtube_shorts',
    description: 'Aged Daily Chronicle newspaper header banner with burning bottom edge flames and ash embers.',
    style: {
      fontFamily: '"Times New Roman", "Playfair Display", serif',
      fontSize: 50,
      activeWordColor: '#1C1917',
      inactiveWordColor: '#44403C',
      useBackgroundPill: false,
      backgroundColor: '#F5E6C8',
      strokeColor: '#F5E6C8',
      strokeWidth: 1,
      shadowColor: 'rgba(234, 88, 12, 0.8)',
      shadowBlur: 16,
      shadowOffsetY: 2,
      animationType: 'burning_newspaper_headline',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.2,
      glowIntensity: 1.25,
      particleFxEnabled: true,
    },
  },
  {
    id: 'underwater_aquarium_bubble_reef',
    name: '🫧 Deep Sea Oceanic Aquarium & Coral Bubbles',
    platform: 'instagram_reels',
    description: 'Deep azure ocean backdrop with rising translucent air bubbles and gently swaying seaweed fronds.',
    style: {
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 50,
      activeWordColor: '#67E8F9',
      inactiveWordColor: '#E0F2FE',
      useBackgroundPill: false,
      backgroundColor: 'rgba(15, 23, 42, 0.9)',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(6, 182, 212, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 2,
      animationType: 'underwater_aquarium_bubble_reef',
      maxWordsPerLine: 3,
      textTransform: 'capitalize',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.22,
      glowIntensity: 1.35,
      particleFxEnabled: true,
    },
  },
  {
    id: 'blueprint_architect_cad_grid',
    name: '📐 Architectural CAD Blueprint & Grid Schematics',
    platform: 'youtube_shorts',
    description: 'Technical Prussian blue CAD drafting blueprint with coordinate grid lines, dimension markers, and scale notes.',
    style: {
      fontFamily: 'monospace, "Courier New", sans-serif',
      fontSize: 48,
      activeWordColor: '#BAE6FD',
      inactiveWordColor: '#F0F9FF',
      useBackgroundPill: false,
      backgroundColor: '#0F2B5C',
      strokeColor: '#0F2B5C',
      strokeWidth: 2,
      shadowColor: 'rgba(96, 165, 250, 0.9)',
      shadowBlur: 16,
      shadowOffsetY: 2,
      animationType: 'blueprint_architect_cad_grid',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.18,
      glowIntensity: 1.2,
      particleFxEnabled: true,
    },
  },
  {
    id: 'neon_glass_gas_tube_sign_flicker',
    name: '💡 Retro Neon Glass Gas Tube Sign & Standoffs',
    platform: 'tiktok',
    description: 'Luminous bent glass neon tube lettering mounted on wall brackets with realistic high-voltage flicker.',
    style: {
      fontFamily: '"Montserrat", sans-serif',
      fontSize: 54,
      activeWordColor: '#FBCFE8',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(10, 10, 15, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(244, 63, 94, 0.95)',
      shadowBlur: 28,
      shadowOffsetY: 2,
      animationType: 'neon_gas_tube_flicker',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.26,
      glowIntensity: 1.5,
      particleFxEnabled: true,
    },
  },
  {
    id: 'wild_west_wanted_poster_wood',
    name: '🤠 Wild West Wanted Dead or Alive Poster',
    platform: 'tiktok',
    description: 'Rustic weathered wood grain reward poster with decorative filigree border and lead bullet hole impacts.',
    style: {
      fontFamily: '"Playfair Display", "Times New Roman", serif',
      fontSize: 50,
      activeWordColor: '#451A03',
      inactiveWordColor: '#78350F',
      useBackgroundPill: false,
      backgroundColor: '#E7D3A7',
      strokeColor: '#E7D3A7',
      strokeWidth: 1,
      shadowColor: 'rgba(0, 0, 0, 0.6)',
      shadowBlur: 12,
      shadowOffsetY: 3,
      animationType: 'western_wanted_poster_wood',
      maxWordsPerLine: 3,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.24,
      glowIntensity: 1.15,
      particleFxEnabled: true,
    },
  },
  {
    id: 'submarine_sonar_radar_screen',
    name: '📡 Submarine Sonar Radar CRT Screen & Sweep',
    platform: 'youtube_shorts',
    description: 'Military submarine radar with rotating phosphor sweep beam, distance rings, and target blip pulse.',
    style: {
      fontFamily: 'Orbitron, monospace',
      fontSize: 50,
      activeWordColor: '#86EFAC',
      inactiveWordColor: '#ECFDF5',
      useBackgroundPill: false,
      backgroundColor: 'rgba(0, 20, 10, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(16, 185, 129, 0.95)',
      shadowBlur: 24,
      shadowOffsetY: 2,
      animationType: 'radar_sonar_submarine_ping',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.24,
      glowIntensity: 1.4,
      particleFxEnabled: true,
    },
  },
  {
    id: 'street_graffiti_spray_paint_drip',
    name: '🎨 Street Aerosol Graffiti Spray & Paint Drips',
    platform: 'tiktok',
    description: 'Vibrant urban aerosol spray paint mist cloud with heavy dripping runs and realistic paint splatter dots.',
    style: {
      fontFamily: 'Impact, "Black Han Sans", sans-serif',
      fontSize: 56,
      activeWordColor: '#FEF08A',
      inactiveWordColor: '#FFFFFF',
      useBackgroundPill: false,
      backgroundColor: 'rgba(20, 20, 20, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: 'rgba(234, 179, 8, 0.95)',
      shadowBlur: 22,
      shadowOffsetY: 3,
      animationType: 'graffiti_spraycan_drip_splat',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.3,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
  {
    id: 'mystic_tarot_alchemy_sigil_circle',
    name: '🔮 Mystic Tarot Alchemy Pentagram Sigil & Runes',
    platform: 'instagram_reels',
    description: 'Golden alchemical sigil circle with spinning sacred geometry pentagram and orbiting ancient Norse runes.',
    style: {
      fontFamily: '"Cinzel", "Playfair Display", serif',
      fontSize: 52,
      activeWordColor: '#FEF08A',
      inactiveWordColor: '#FFFBEB',
      useBackgroundPill: false,
      backgroundColor: 'rgba(25, 10, 0, 0.95)',
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: 'rgba(245, 158, 11, 0.95)',
      shadowBlur: 26,
      shadowOffsetY: 2,
      animationType: 'magic_alchemy_tarot_sigil',
      maxWordsPerLine: 2,
      textTransform: 'uppercase',
      positionYPercent: 70,
      positionXPercent: 50,
      emojiEnabled: true,
      autoEmojiKeywords: true,
      activeScaleFactor: 1.28,
      glowIntensity: 1.45,
      particleFxEnabled: true,
    },
  },
];

